on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - fork4424
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 9 12 * * *
name: Semgrep
jobs:
  buildmavenDepTree: 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean compile
      - name: Build Dependency Tree
        run: mvn dependency:tree -DoutputFile=maven_dep_tree.txt
      - name: Upload Dependency Tree Artifact     
        uses: actions/upload-artifact@v3
        with:
          name: mavendeptree
          path: maven_dep_tree.txt
  semgrep:
    needs: buildmavenDepTree
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact from previous job
        uses: actions/download-artifact@v3
        with:
          name: mavendeptree 
      - run: semgrep ci
